version: '3'
services:
  zookeeper:
    image: spiside/kafka-cluster
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      RUN_TYPE: "zookeeper"
  kafka:
    image: spiside/kafka-cluster
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      RUN_TYPE: "kafka"
    links:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/docker.sock
  kafka2:
      image: spiside/kafka-cluster
      hostname: kafka
      ports:
        - "9093:9092"
      environment:
        RUN_TYPE: "kafka"
      links:
        - zookeeper
      volumes:
        - /var/run/docker.sock:/docker.sock
  kafka3:
      image: spiside/kafka-cluster
      hostname: kafka
      ports:
        - "9094:9092"
      environment:
        RUN_TYPE: "kafka"
      links:
        - zookeeper
      volumes:
        - /var/run/docker.sock:/docker.sock
